// Code generated by protoc-gen-go.
// source: basetype.proto
// DO NOT EDIT!

/*
Package dbaccess is a generated protocol buffer package.

It is generated from these files:
	basetype.proto
	test.proto

It has these top-level messages:
	Double
	Float
	Int32
	UInt32
	Int64
	UInt64
	String
	Bool
	Date
	Student
*/
package dbaccess

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Double struct {
	Data float64 `protobuf:"fixed64,1,opt,name=data" json:"data,omitempty"`
}

func (m *Double) Reset()                    { *m = Double{} }
func (m *Double) String() string            { return proto.CompactTextString(m) }
func (*Double) ProtoMessage()               {}
func (*Double) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Double) GetData() float64 {
	if m != nil {
		return m.Data
	}
	return 0
}

type Float struct {
	Data float32 `protobuf:"fixed32,1,opt,name=data" json:"data,omitempty"`
}

func (m *Float) Reset()                    { *m = Float{} }
func (m *Float) String() string            { return proto.CompactTextString(m) }
func (*Float) ProtoMessage()               {}
func (*Float) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Float) GetData() float32 {
	if m != nil {
		return m.Data
	}
	return 0
}

type Int32 struct {
	Data int32 `protobuf:"varint,1,opt,name=data" json:"data,omitempty"`
}

func (m *Int32) Reset()                    { *m = Int32{} }
func (m *Int32) String() string            { return proto.CompactTextString(m) }
func (*Int32) ProtoMessage()               {}
func (*Int32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Int32) GetData() int32 {
	if m != nil {
		return m.Data
	}
	return 0
}

type UInt32 struct {
	Data uint32 `protobuf:"varint,1,opt,name=data" json:"data,omitempty"`
}

func (m *UInt32) Reset()                    { *m = UInt32{} }
func (m *UInt32) String() string            { return proto.CompactTextString(m) }
func (*UInt32) ProtoMessage()               {}
func (*UInt32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UInt32) GetData() uint32 {
	if m != nil {
		return m.Data
	}
	return 0
}

type Int64 struct {
	Data int64 `protobuf:"varint,1,opt,name=data" json:"data,omitempty"`
}

func (m *Int64) Reset()                    { *m = Int64{} }
func (m *Int64) String() string            { return proto.CompactTextString(m) }
func (*Int64) ProtoMessage()               {}
func (*Int64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Int64) GetData() int64 {
	if m != nil {
		return m.Data
	}
	return 0
}

type UInt64 struct {
	Data uint64 `protobuf:"varint,1,opt,name=data" json:"data,omitempty"`
}

func (m *UInt64) Reset()                    { *m = UInt64{} }
func (m *UInt64) String() string            { return proto.CompactTextString(m) }
func (*UInt64) ProtoMessage()               {}
func (*UInt64) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UInt64) GetData() uint64 {
	if m != nil {
		return m.Data
	}
	return 0
}

type String struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *String) Reset()                    { *m = String{} }
func (m *String) String() string            { return proto.CompactTextString(m) }
func (*String) ProtoMessage()               {}
func (*String) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *String) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Bool struct {
	Data bool `protobuf:"varint,1,opt,name=data" json:"data,omitempty"`
}

func (m *Bool) Reset()                    { *m = Bool{} }
func (m *Bool) String() string            { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()               {}
func (*Bool) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Bool) GetData() bool {
	if m != nil {
		return m.Data
	}
	return false
}

type Date struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *Date) Reset()                    { *m = Date{} }
func (m *Date) String() string            { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()               {}
func (*Date) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Date) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Double)(nil), "dbaccess.Double")
	proto.RegisterType((*Float)(nil), "dbaccess.Float")
	proto.RegisterType((*Int32)(nil), "dbaccess.Int32")
	proto.RegisterType((*UInt32)(nil), "dbaccess.UInt32")
	proto.RegisterType((*Int64)(nil), "dbaccess.Int64")
	proto.RegisterType((*UInt64)(nil), "dbaccess.UInt64")
	proto.RegisterType((*String)(nil), "dbaccess.String")
	proto.RegisterType((*Bool)(nil), "dbaccess.Bool")
	proto.RegisterType((*Date)(nil), "dbaccess.Date")
}

func init() { proto.RegisterFile("basetype.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x4a, 0x2c, 0x4e,
	0x2d, 0xa9, 0x2c, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x49, 0x4a, 0x4c,
	0x4e, 0x4e, 0x2d, 0x2e, 0x56, 0x92, 0xe1, 0x62, 0x73, 0xc9, 0x2f, 0x4d, 0xca, 0x49, 0x15, 0x12,
	0xe2, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0c, 0x02, 0xb3, 0x95,
	0xa4, 0xb9, 0x58, 0xdd, 0x72, 0xf2, 0x13, 0x4b, 0x50, 0x24, 0x99, 0x10, 0x92, 0x9e, 0x79, 0x25,
	0xc6, 0x46, 0x28, 0x92, 0xac, 0x50, 0x49, 0xa0, 0xb9, 0xa1, 0x98, 0xb2, 0xbc, 0x28, 0x5a, 0xcd,
	0x4c, 0x50, 0x24, 0x99, 0x51, 0xb5, 0xa2, 0xc9, 0xb2, 0x20, 0x64, 0x83, 0x4b, 0x8a, 0x32, 0xf3,
	0xd2, 0x51, 0x64, 0x39, 0xa1, 0xb2, 0x52, 0x5c, 0x2c, 0x4e, 0xf9, 0xf9, 0x39, 0x28, 0x72, 0x1c,
	0x08, 0x39, 0x97, 0xc4, 0x92, 0x54, 0x6c, 0xfa, 0x92, 0xd8, 0xc0, 0xe1, 0x62, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xc5, 0xc4, 0x7b, 0x36, 0x29, 0x01, 0x00, 0x00,
}
